APP_NAME: COVID-19 Simulation
LOG_LEVEL: INFO

SIMULATION:
  PARAMS:
    EPISODES: 500 # interpreted as days
    TOTAL_NUMBER_OF_AGENTS: 1_000
    TRAVELLING_NUMBER_OF_AGENTS: 5
    VACCINATED_PRCNT_OF_AGENTS: 0.1 # between 0 and 1
    FIRST_DOSE_IMMUNE_TIME: 12  # days
    FIRST_DOSE_IMMUNE_PRCNT: 0.52  # percentage
    SECOND_DOSE_IMMUNE_TIME: 28 # 21 + 7 days, a week after the second dose
    SECOND_DOSE_IMMUNE_PRCNT: 0.95  # percentage
    NO_MORE_SICK_AGENTS_TRAVELLING_STEP: 365 # after x days no more sick agents got into the simulation. only recovered or healthy
    SIZE: 150 # environment size on each axis
    PIXELS: 1500 # environment size on each axis
    RANDOM_LIMIT: 20 # maximum value that each agent can move from its position (+ or -)
    AGENTS_MOVEMENT_PERCENTAGE: 1 # percentage of the agents that moves in the step
    QUARANTINE_X: -10 # should be negative or greater than SIZE to get out of the env
    QUARANTINE_Y: -10 # should be negative or greater than SIZE to get out of the env
    DEAD_X: -1 # should be negative or greater than SIZE to get out of the env
    DEAD_Y: -1 # should be negative or greater than SIZE to get out of the env
    QUARANTINE_PERCENTAGE: 0.1 # number of agents detected and starting quarantine
    QUARANTINE_DAYS: 10 # number o days to wait until starting to put agents in quarantine
  STATIC:
    PARAMS:
      SICK_PRCNTG: 0.2 # number of sick agents when starting the simulation
      ASYMP_PRCNTG: 0.1 # number of asymptomatic agents when starting the simulation
      IMMMUNE_IMR_PRCNTG: 0.1 # number of agents with immune system resposnse as Immune when starting the simulation, only healthy agents can be immune
      ASYMP_IMR_PRCNTG: 0.3 # number of agents with immune system resposnse as Asymptomatic when starting the simulation
      MOD_IMR_PRCNTG: 0.3 # number of agents with immune system resposnse as Moderately Infected when starting the simulation
      SEVERE_IMR_PRCNTG: 0.2 # number of agents with immune system resposnse as severe infected when starting the simulation
      DEAD_IMR_PRCNTG: 0.1 # number of agents with immune system resposnse as Deadly infected when starting the simulation
      AGENTS_WEARING_MASK_PRCNTG: 0.1 # number of agents wearing a mask when starting the simulation
  AGENT:
    PARAMS:
      HEALTH_ARRAY_SICK_P: 0.02 # probabilities of being of one type in random simulation with no static values
      HEALTH_ARRAY_ASYMP_P: 0.001
      HEALTH_ARRAY_HEALTHY_P: 0.979
      RECOVERY_SEQUELS_P: 0.4 # Probability of recovering but with sequels
      # probability of of being infected when being in contact with a type of agent
      SICK_P: 0.8
      ASYMPTOMATIC_P: 0.1
      HEALTHY_P: 0.1
      SOCIAL_DISTANCE: 2 # initial minimal distance between agents
      # can move to a position x y +SOCIAL_DISTANCE_STEP and -SOCIAL_DISTANCE_STEP
      SOCIAL_DISTANCE_STEP: 0
      # distance that triggers a possible contagious if one of the agents is infected
      CONTAGIOUS_DISTANCE: 2
      # number of times the agent tries to keep the social distance until quit. Note: It slows down the simulation speed
      SOCIAL_DISTANCE_TRIES: 1
      INFECTED_DAYS_THRESHOLD_FOR_INFECTED: 15 # after X days agents recover
      INFECTED_DAYS_THRESHOLD_FOR_DEAD: 5  # agents die after X days if immune system type IMR_DEADLY_INFECTED
      INFECTED_DAYS_THRESHOLD_FOR_NOT_CONTAGIOUS: 10 # stop the virus propagation
      CONTAGIOUS_AGENT_MASK: 0.05 # agent in contact with is sick but wears a mask
      HEALTHY_AGENT_MASK: 0.15 # agent wears a mask
      CONTAGIOUS_AGENT_MASK_HEALTHY_MASK: 0.7 # both agents in contact wear a mask
      CONTAGIOUS_AGENT_NO_MASK_HEALTHY_NO_MASK: 1 # neither one wears it
  VISUALIZATION:
    PARAMS:
      COLORS_DICT: #BGR
        SICK_COLOR: [0, 0, 255] # red
        ASYMPTOMATIC_COLOR: [0, 115, 255] # orange
        WITH_DISEASES_SEQUELAES_COLOR: [255, 0, 196] # purple
        TOTAL_RECOVERY_COLOR: [0, 255, 255] # yellow
        DEAD_COLOR: [0, 0, 0] # dead is black
        HEALTHY_COLOR: [0, 255, 0] # green
      SIZES:
        FOUR_PLOTS_FIG_SIZE_X: 9
        FOUR_PLOTS_FIG_SIZE_Y: 8
        ALL_DATA_PLOT_FIG_SIZE_X: 10
        ALL_DATA_PLOT_FIG_SIZE_Y: 300
        SIMULATION_GRAPHICS_SIZE_X: 900
        SIMULATION_GRAPHICS_SIZE_Y: 900
