APP_NAME: COVID-19 Simulation
LOG_LEVEL: INFO

SIMULATION:
  PARAMS:
    EPISODES: 500 # interpreted as days
    TOTAL_NUMBER_OF_AGENTS: 2_000
    SIZE: 200 # environment size on each axis
    RANDOM_LIMIT: 20 # maximum value that each agent can move from its position (+ or -)
    AGENTS_MOVEMENT_PERCENTAGE: 1 # percentage of the agents that moves in the step
    QUARENTINE_X: -10 # should be negative or greater than SIZE to get out of the env
    QUARENTINE_Y: -10 # should be negative or greater than SIZE to get out of the env
    DEAD_X: -1 # should be negative or greater than SIZE to get out of the env
    DEAD_Y: -1 # should be negative or greater than SIZE to get out of the env
    QUARENTINE_PERCENTAGE: 0.1 # number of agents detected and starting quarentine
    QUARENTINE_DAYS: 15 # number o days to wait until starting to put agents in quarentine
  STATIC:
    PARAMS:
      SICK_NBR: 50 # number of sick agents when starting the simulation
      ASYMP_NBR: 50 # number of asymptomatic agents when starting the simulation
      IMMMUNE_IMR_NBR: 10 # number of agents with immune system resposnse as Immune when starting the simulation, only healthy agents can be immune
      ASYMP_IMR_NBR: 300 # number of agents with immune system resposnse as Asymptomatic when starting the simulation
      MOD_IMR_NBR: 690 # number of agents with immune system resposnse as Moderately Infected when starting the simulation
      HIGH_IMR_NBR: 900 # number of agents with immune system resposnse as Highly infected when starting the simulation
      DEAD_IMR_NBR: 100 # number of agents with immune system resposnse as Deadly infected when starting the simulation
      AGENTS_WEARING_MASK: 100 # number of agents wearing a mask when starting the simulation
  AGENT:
    PARAMS:
      HEALTH_ARRAY_SICK_P: 0.02 # probabilities of being of one type in random simulation with no static values
      HEALTH_ARRAY_ASYMP_P: 0.001
      HEALTH_ARRAY_HEALTHY_P: 0.979
      RECOVERY_SEQUELS_P: 0.4 # Probability of recovering but with sequels
      # probability of of being infected when being in contact with a type of agent
      SICK_P: 0.8
      ASYMPTOMATIC_P: 0.1
      HEALTHY_P: 0.1
      SOCIAL_DISTANCE: 0 # initial minimal distance between agents
      # can move to a position x y +SOCIAL_DISTANCE_STEP and -SOCIAL_DISTANCE_STEP
      SOCIAL_DISTANCE_STEP: 0
      # distance that triggers a possible contagious if one of the agents is infected
      CONTAGIOUS_DISTANCE: 2
      INFECTED_DAYS_THRESHOLD_FOR_INFECTED: 15 # after X days agents recover
      INFECTED_DAYS_THRESHOLD_FOR_DEAD: 5  # agents die after X days if immune system type IMR_DEADLY_INFECTED
      INFECTED_DAYS_THRESHOLD_FOR_NOT_CONTAGIOUS: 10 # stop the virus propagation
      CONTAGIOUS_AGENT_MASK: 0.05 # agent in contact with is sick but wears a mask
      HEALTHY_AGENT_MASK: 0.15 # agent wears a mask
      CONTAGIOUS_AGENT_MASK_HEALTHY_MASK: 0.7 # both agents in contact wear a mask
      CONTAGIOUS_AGENT_NO_MASK_HEALTHY_NO_MASK: 1 # neither one wears it
  VISUALIZATION:
    PARAMS:
      COLORS_DICT: #BGR
        SICK_COLOR: [0, 0, 255] # red
        ASYMPTOMATIC_COLOR: [0, 115, 255] # orange
        WITH_DISEASES_SEQUELAES_COLOR: [255, 0, 196] # purple
        TOTAL_RECOVERY_COLOR: [0, 255, 255] # yellow
        DEAD_COLOR: [0, 0, 0] # dead is black
        HEALTHY_COLOR: [0, 255, 0] # green
      SIZES:
        FOUR_PLOTS_FIG_SIZE_X: 9
        FOUR_PLOTS_FIG_SIZE_Y: 8
        ALL_DATA_PLOT_FIG_SIZE_X: 12
        ALL_DATA_PLOT_FIG_SIZE_Y: 10
        SIMULATION_GRAPHICS_SIZE_X: 900
        SIMULATION_GRAPHICS_SIZE_Y: 900
